CREATE TABLE CLIENTES
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME VARCHAR(255),
NASCIMENTO VARCHAR(12),
TELEFONE VARCHAR(30),
ENDERECO VARCHAR(255),
EMAIL VARCHAR(255),
CPF VARCHAR(14) UNIQUE,
CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID)
);

CREATE TABLE PRODUTOS
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME VARCHAR(255),
DESCRICAO VARCHAR(255),
MARCA VARCHAR(50),
NUMPRODUTO VARCHAR(4) UNIQUE,
FABRICACAO VARCHAR(12),
QTD INTEGER,
VALOR DOUBLE,
PRIMARY KEY (ID)
) ;

CREATE TABLE VENDA 
(
IDCARRINHO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
VALORUNI_FK DOUBLE,
VALOR_FK DOUBLE,
PRODUTO_FK VARCHAR(255),
QTD_FK INTEGER,
PRIMARY KEY (IDCARRINHO)
) ;

CREATE TABLE RELATORIO
(
IDRELATORIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
VALOR_TOTAL DOUBLE,
CLIENTE VARCHAR(255),
QTD_ITEMS INTEGER,
DATA_VENDA VARCHAR(100),
PRIMARY KEY (IDRELATORIO)
) ;

CREATE TABLE INFORELATORIO
(
IDRELATORIO INTEGER,
VALOR_TOTAL DOUBLE,
QTD_ITEMS INTEGER,
PRODUTO VARCHAR(255),
FOREIGN KEY (IDRELATORIO) REFERENCES RELATORIO (IDRELATORIO)
) ;